### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by tanyaofei** [ApliNi/BedrockMinerPlugin#1]
感谢作者分享，我也是个开发者，参造你分享的源码也实现了类似的功能～
下面是在看源码的时候发现的一个问题：

+ 在非主线程里调用 sound 有概率直接炸服，服务端会直接退出。这个问题产生的原因是 sound api 会用到一个随机值，而 `RandomSource` 会在执行时检查并发，如果产生了并发服务端会异常结束。建议所有 `写` 操作的 api 都使用主线程。

**Comment by ApliNi** [comment]
感谢提出建议! 我是插件开发的新手. 关于这个问题我在网络上没有找到过相关的帖子, 我尝试使用很多线程并循环运行也没有测试出问题, 它可能已经被修复?

**Comment by tanyaofei** [comment]
不好意思忘了回复，我在这里给 paper 提过 issue。https://github.com/PaperMC/Paper/issues/9490

**Comment by ApliNi** [comment]
嗯嗯，我在这里使用异步代替了多线程，如果这个问题真的存在，那么它应该能被解决 :)
